### ISSUE TITLE
Missing node lengths on phylogenetic trees & node.name is returning values

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#12]
The branch lengths are coming directly from FastTree output or being appended using skbio's append method in TreeNode.  When FastTree determines there is no length it gives it a value of "0.0" so I am not sure why there are lengths of "none".  Maybe this is the skbio TreeNode?  I'm not sure.

I checked a backbone tree with skbio (which is just 18S aligned sequences run on FastTree *without* any other modification or skbio methods) and it looks like it's outputting a length for some node.names when I traverse through the tree.  So I am not sure what's going.

I also ran the same script as below on a full ghost-tree .nwk and it looks like what it's doing is adding the "None" value to every insertion it makes into the backbone.  So possibly everywhere there is an insertion of a "mini" tree, there is a "None" value too.

I'll email some test files.

**I used this to check the backbone tree:**

from skbio import TreeNode

backbone_tree = TreeNode.read("nr_backbone_tree_gt.nwk", format="newick")

output = open("backbone_tree_analysis_file_032915.txt", "w")

for node in backbone_tree.traverse():
    output.write(str(node.name)+"\t"+str(node.length)+"\n")

output.close()

**Small output from analysis file (first column is node.name, 2nd is node.length):**

None	None
0.788	0.00128
0.806	0.00053
0.981	0.00055
AY665783.1.1694	0.00137
0.044	0.00055
AY657010.1.1771	0.00131
AF426952.1.1784	0.00618
0.737	0.00064
0.973	0.00054
0.968	0.00055
AY771602.1.1776	0.00066
0.492	0.00055
0.882	0.00132

**Comment by JTFouquier** [comment]
Hi @jairideout, I think this is more of a ghost-tree issue than just a general question like it was before, so I relocated it here.  I emailed test files as well since I can't attach them here.  I'd be happy to clarify anything.

**Comment by jairideout** [comment]
@ebolyen can you look into this one? I think you have the most experience with `TreeNode` and the newick parsing.

**Comment by ebolyen** [comment]
@JTFouquier @jairideout 

It looks like everything is generally working as expected. I checked the `ghost-tree_97_80clusters.nwk` file and got this output:
http://hastebin.com/puyuqirafo.py

What I suspect is happening is when you append your subtrees, each subtree has no length (because it is a root node, and a length on a root is generally meaningless). NodeTree doesn't know or really care about this, so it appends the root onto your backbone and moves on. The result is that you have a node with no length at the start of each subtree (the former root). Depending on how you want to handle this, you could either set the subtree root to a 0 length (effectively saying that they are the same node), or put the roots children on the node you were appending to anyways (now they literally are the same node). 

Hopefully this is the issue, if not let me know.

**Comment by ebolyen** [comment]
@JTFouquier PR #15 submitted as an example of what I think is going wrong.

**Comment by JTFouquier** [comment]
Thanks! That makes sense regarding the root and I'll look into your example fix and work on the code. But I am a bit confused about node.name (in the example I pasted above).  Shouldn't those be the accession numbers?

**Comment by JTFouquier** [comment]
*because that 2 column list I pasted is for the backbone tree which did not have any mini trees appended yet.  It's just a FastTree output.

**Comment by ebolyen** [comment]
@JTFouquier That would depend on what FastTree does.

**Comment by JTFouquier** [comment]
I mentioned this via email, but node.extend(mini_tree.children[:]) works perfectly and solved my troubles with Simsam.py issue which was how this was originally discovered.  Thanks again!
