### ISSUE TITLE
ghost-tree filter-alignment-positions works, but unit testing is challenging...

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#14]
@ebolyen, @jairideout, @johnchase:  we worked on filter.py (filter-alignment-positions) in AZ, but I just moved it into 3 functions and got rid of the workaround (aln = aln.omit_gap_positions(1.0 - np.finfo(float).eps)) after skbio was updated.  

https://github.com/JTFouquier/ghost-tree/blob/master/ghosttree/filter.py

@ebolyen said it would be difficult to test.  o. m. g. 

Is it safe to say that enough of this script uses skbio that I don't really need to unit test it?  :)  If I need to test it, any tips?  I have tried unit testing this so many times.  

Thanks!

**Comment by jairideout** [comment]
The entropy filtering code is probably the most important part to test since there is a little bit of code that isn't just calling into scikit-bio. What specifically is making it difficult to unit test these functions? They seem pretty well-defined since they always take a filepath or filehandle and return an `skbio.Alignment` object.

What I'd do is define a small alignment in some sort of alignment file format (e.g., FASTA), store that in a `StringIO`, and use that as input to `filter_positions`. You can then compare the filtered alignment that's returned to an `skbio.Alignment` object that you've created with the expected contents.

**Comment by JTFouquier** [comment]
For some reason I am just getting odd errors when unit testing (like it thinks it's writing blank sequences).  I posted some pics below.  

That's what I have been trying for the unit tests.  It should be very similar to what you guys taught me and how I've been testing the other pieces.  I'm probably just missing something.

Thank you!

Works fine in ghost-tree:
![screen shot 2015-04-01 at 9 26 52 pm](https://cloud.githubusercontent.com/assets/7920357/6957858/8d0d44d2-d8b7-11e4-91a4-1970d6b0d255.png)

One attempt at the unit test (that isn't a "pipe"... just the cursor):
![screen shot 2015-04-01 at 9 36 43 pm](https://cloud.githubusercontent.com/assets/7920357/6957860/8d137aaa-d8b7-11e4-9f26-c8da1a04b199.png)

The error from unit test:
![screen shot 2015-04-01 at 9 36 03 pm](https://cloud.githubusercontent.com/assets/7920357/6957859/8d120b2a-d8b7-11e4-8264-e0ac5a655ce8.png)

**Comment by jairideout** [comment]
It looks like you're printing one of the `Alignment` objects in your test. When you print an alignment, it is displayed in FASTA format, but the error message is saying that the first sequence in the alignment is empty (which isn't valid for FASTA format). Is it possible that all positions are being filtered out?

Also I noticed in your test code that you're wrapping `maximum_gap_frequency` and `maximum_position_entropy` in `StringIO`. Those shouldn't be wrapped in `StringIO` because you want the floating point values to be passed to the filter function. `StringIO` is only necessary for creating a mock file-like object. This could be causing all positions to be filtered out.

**Comment by JTFouquier** [comment]
Oh, yes that makes sense.  I thought wrapping them was a requirement for something in Unit Test.  I'll fix that.  That's probably it.  Hopefully!!

**Comment by JTFouquier** [comment]
Aaaaaah that was it. :anguished:   It looks so obvious now...  big sigh... thank you :)

**Comment by jairideout** [comment]
No problem, glad it's working!
