### ISSUE TITLE
FastTree warnings need to be handled differently

### ISSUE THREAD

**Issue by johnchase** [JTFouquier/ghost-tree#25]
Currently `ghost-tree scaffold hybrid-tree` runs FastTree which in turn generates an error for any non-nucleotide character, for example: `Ignored unknown character K (seen 2 times)`. This means that the terminal is spammed with warnings. Running this command in an IPython notebook will cause the notebook to crash. 

This could be dealt with either a with script that filters invalid characters prior to running `ghost-tree scaffold hybrid-tree` so that `ghost-tree scaffold hybrid-tree` would fail if any invalid characters were present. Or by a single warning that says "non-nucleotide characters were detected and ignored"

**Comment by JTFouquier** [comment]
Hi John,

I emailed you a file, so hopefully you can give me your input.  I'm not sure why FastTree provides these errors.  They don't seem to make much sense to me.  For that file I sent, I get the following errors from FastTree:

Warning! Found "." character(s). These are treated as gaps
Ignored unknown character R (seen 5 times)
Ignored unknown character X (**seen 105 times**)
Ignored unknown character Y (seen 4 times)

But when I search for those characters in the fasta file I get:
R = 1883 times
X = **29 times**
Y = 1766 times

It seems like the most common character of the three (X... is actually the least common character when I search the fasta file).

Am I missing something obvious?  Any thoughts?  Thanks!  At first I wanted to make sure it wasn't trying to align the taxonomy names, but it won't do that.  It would give the error that the sequences are different lengths.

**Comment by johnchase** [comment]
@JTFouquier The numbers you are seeing are the total number of characters observed in a file including in the headers. The R and Y character counts are the correct counts found in the sequences, however there are no 'X' characters anywhere in the file you sent me. I'm investigating what that could mean, though I have not yet found an answer.

**Comment by JTFouquier** [comment]
@johnchase I double checked this. Yeah, I see what you mean about those x's and not being in the sequence part.  Now I'm just all confused. I think I thought that FastTree was searching in the headers too because of those X's. (Sorry this isn't really the point of this issue, but it was odd behavior and I want to understand it).

**Comment by gregcaporaso** [comment]
I think the way to handle this (and this is really @johnchase's idea as we discussed this yesterday) will be to redirect ``FastTree`` standard error to a log file, and then present a single message at the end if anything was written to that file, along the lines of:

```FastTree encountered errors and/or warnings. You should review those in the FastTree log file at <filepath>.```

**Comment by johnchase** [comment]
@JTFouquier would it be possible to load the tiny_alignment_fasttree_test.fasta into the ghost-tree repository somewhere, perhaps in the legacy directory, and link to it in this issue? I'm still concerned about why FastTree is showing this error
 `Ignored unknown character X (seen 105 times)`
 when 'X' is not actually present in any of the sequences. 


```python
from skbio.alignment import SequenceCollection
seqs = SequenceCollection.read('tiny_alignment_fasttree_test.fasta')
x = 0
y = 0
r = 0
for seq in seqs:
    x += seq.count('X')
    y += seq.count('Y')
    r += seq.count('R')
print x, y, r

0 4 5
```

**Comment by JTFouquier** [comment]
Agreed.  It's confusing.  Here is the file in the ghost-tree repository:

https://github.com/JTFouquier/ghost-tree/blob/master/legacy/tiny_alignment_fasttree_test.fasta

I tried looking at the .c code too.  http://www.microbesonline.org/fasttree/FastTree.c and couldn't figure it out.  Although this is beyond me, one of the programmers at work mentioned that this could be something to do with the byte code & hexadecimal or something.  Basically script thinks it's looking for an X but it really isn't because it got confused with the byte code due to an assignment issue.  (I'm just really stretching for something here)  :)

import re

fasttreefile = open("tiny_alignment_fasttree_test.fasta", "U")

xcount = 0
ycount = 0
rcount = 0

for line in fasttreefile:
    line = line.lower()
    if re.search(">",line):
        pass
    else:
        x = line.count("x")
        xcount+=x
        y = line.count("y")
        ycount+=y
        r = line.count("r")
        rcount+=r

print xcount,ycount,rcount

Included the fasttree command line output:
![screen shot 2015-05-06 at 9 51 25 pm](https://cloud.githubusercontent.com/assets/7920357/7508712/206670e4-f43a-11e4-865b-df571f58d5a3.png)

**Comment by johnchase** [comment]
@wasade you may have more experience with FastTree than Jennifer or me, do you have any thoughts on this?

**Comment by wasade** [comment]
I don't know how the counts are being performed in FastTree. X is not a valid IUPAC DNA character. It would be necessary to follow up with Morgan about this specifically to determine what's going on. What is the FastTree version?

Regarding the output, I recommend running FastTree from `subprocess.Popen` instead of `os.system` as the former will allow you to capture standard error.

**Comment by JTFouquier** [comment]
@johnchase, @wasade I'm using 2.1.7. Version 2.1.8 does the same thing.  

I figured out what it is doing. FastTree is considering "Ns" as "Xs" in the warning messages. 

The characters with counts below are A, C, G, **N**, **R**, U, **Y**.  There are no Xs in the seqs of the file. The counts FastTree provides for the Rs and Ys are correct as shown below.  Might be an escape character with the Ns or something else.  I'll email the developer.  Hopefully this is just an issue with the warning message and doesn't affect the "Ns" in the amino acid alphabet or anything.  

**105471 0 75216 0 0 0 103651 0 0 0 0 0 0 105 0 0 0 5 0 0 100278 0 0 0 4 0**

**Comment by gregcaporaso** [comment]
> Regarding the output, I recommend running FastTree from subprocess.Popen instead of os.system as the former will allow you to capture standard error.

:+1: This would easily support what I was suggesting above (catch stderr, write it to file, and give the user a single warning if anything is written to that file).

**Comment by gregcaporaso** [comment]
Note that `X` in the amino acid alphabet has the same meaning as `N` in the nucleotide alphabets (i.e., any character in the alphabet), so it could just be a typo in the error message.

**Comment by JTFouquier** [comment]
I listed subprocess.Popen as a separate issue earlier.  I'll do that this weekend.  Thanks!

**Comment by jamespharper** [comment]
I have reproduced this error on my computer and attempted to determine its cause.  It seems that FastTree is reporting that it is counting instances of the letter "X" when it is actually counting instances of the letter "N." This may be caused by a translation error from hexadecimal, which is used in the FastTree algorithm.

Sorry I can't be of more help!

**Comment by JTFouquier** [comment]
Yeah I said that. See above. :)

**Comment by JTFouquier** [comment]
@johnchase @gregcaporaso @wasade, FastTree warnings are redirected to a log file using subprocess.Popen.  This should stop crashing the iPython notebook.  I also solved the issue related to FastTree Xs/Ns...  FastTree renames Ns to Xs in the code, but it doesn't tell you this anywhere in the directions, which is obviously a little confusing. (/* If nucleotide sequences, replace U with T and N with X */) .

**Comment by gregcaporaso** [comment]
All sounds good, thanks @JTFouquier!
