### ISSUE TITLE
beta_diversity_through_plots

### ISSUE THREAD

**Issue by aves920** [JTFouquier/ghost-tree#72]
Hi, 

I'm trying to run beta_diversity_through_plots for ITS1 data in Qiime 1.9 using ghost-tree and and I'm not sure that it is working correctly.  No errors come up, but I have left script running for hours, but my UniFrac folders remain empty.  Should it normally take this long? I only have 12 samples and one variable.

I have filtered my biom table to contain only only the accession numbers present in the 97_100 ghost tree (have attached the txt file as can't upload the biom format).  

Is it something to do with the qiime_config values? I see in the log file gg_13_8_otus is the default.

Thank you for your help in advance :)
Anna

[plaque_its_mapping_file.txt](https://github.com/JTFouquier/ghost-tree/files/335949/plaque_its_mapping_file.txt)
[parameters_beta_diversity.txt](https://github.com/JTFouquier/ghost-tree/files/335950/parameters_beta_diversity.txt)
[plaque_final_otu_table.txt](https://github.com/JTFouquier/ghost-tree/files/335953/plaque_final_otu_table.txt)

**Comment by JTFouquier** [comment]
Hi Anna, I am responding through email because I am just about to go out of
the country for my honeymoon and move out of state right away after
returning. Unfortunately, I will not be able to address this for about 6
weeks. Feel free to keep updating this issue if you have anything to add.
Thanks! :)

**Comment by aves920** [comment]
Hi Jennifer,

Thanks for your email.  No worries, I'll see what I can do in the mean time
:)

Enjoy your honeymoon!!

Anna

**Comment by jairideout** [comment]
@aves920 in the meantime you might consider posting this on the [QIIME forum](https://groups.google.com/forum/#!forum/qiime-forum), since it could be more of a QIIME-related issue than ghost-tree. If you post your issue there, please be sure to include a link back to this issue.

**Comment by JTFouquier** [comment]
@aves920, I am sorry for all the excuses. We also just moved from CA to CO (USA), and I'm so behind on everything. I'm going to sit down and catch up on work early next week. Thanks for understanding! In the meantime, please let me know if you want to add anything to this issue.

**Comment by aves920** [comment]
Hi Jennifer,

No worries, I'm actually in Europe for a month now anyway, back in October
- so no rush!

Cheers,
Anna

**Comment by JTFouquier** [comment]
Hi Anna, 

So, I'm looking at your OTU table, and it seems pretty sparse on OTUs. I'm not sure how common that is, since I haven't worked with that many datasets, but I am wondering if that might be what is giving you trouble. [Here](https://github.com/JTFouquier/ghost-tree/files/514414/table.txt) is the OTU table from the ghost-tree paper so you can see that there are a lot more OTUs. "RR" were are my public restroom samples, and "FB" were the saliva samples. 
 
Have you tried using the non-phylogenetic methods just to see how they look and if this works for you?  Let me know what you get with those.  I would always do the unweighted and weighted for both non-phylogenetic and phylogenetic metrics. It gets tedious, but it helped me at least to make sure I was doing everything correctly. 

@jairideout, I know you've analyzed more microbiome datasets than I have, so you might have a feeling about these files. Can you take a quick peek at the files she attached in the initial post?  

Thanks!

**Comment by jairideout** [comment]
@JTFouquier I'm traveling next week so won't be available to look at this until the week of 10/17. Since this doesn't sound like a ghost-tree-specific issue, can you post it on the QIIME forum? You'll get help much faster that way.

**Comment by JTFouquier** [comment]
Thanks @jairideout, I posted this on the QIIME forum, so hopefully we'll get a response. Have fun on your trip!  ✈️ 

@aves920, hope you also had a great time in Europe!  [Here is the link to the QIIME forum post,](https://groups.google.com/forum/#!topic/qiime-forum/lKMchIwv0no) so hopefully someone will help. If anything changes, please update this issue. Thanks!

**Comment by ElDeveloper** [comment]
Is there a tree that I can use and the exact command that was executed, this way I'll see if it's a problem with QIIME or something else.
