### ISSUE TITLE
ghost-tree update to skbio 5.0? Yes or no?

### ISSUE THREAD

**Issue by JTFouquier** [JTFouquier/ghost-tree#77]
2 qs:

1) First, I figure I'll need to update to Python3 for QIIME2 anyways, so that makes sense for ghost-tree unless anyone feels strongly against Python3 for ghost-tree.  

2)  So I figure I should also update skbio, but I'm running into errors such as: 
<img width="565" alt="screen shot 2016-10-18 at 6 22 51 pm" src="https://cloud.githubusercontent.com/assets/7920357/19501117/192c26b6-9560-11e6-838a-fc52a8a5f14b.png">
(this is just an example, no need to trouble shoot this for me)

My 2nd question is should I just familiarize myself with the newer releases of skbio (5.0) or stick to 0.2.3?  

Thanks! 

@jairideout @gregcaporaso @ebolyen

**Comment by gregcaporaso** [comment]
Hi @JTFouquier, I'd highly recommend transitioning to skbio 0.5.0. You'll really want that for QIIME 2 plugins. Going through the [ChangeLog](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md) will help you figure out what specifically has changed - let us know if you have specific questions from there and we'll be happy to advise.

**Comment by JTFouquier** [comment]
@gregcaporaso thanks! It's going well. The skbio change log is really clear.

**Comment by JTFouquier** [comment]
@jairideout, @gregcaporaso, what is the new way to do this line (working with a .fasta file)...  
https://github.com/JTFouquier/ghost-tree/blob/master/ghosttree/filter.py#L14

I tried the TabularMSA and AlignmentStructure objects, and I'm getting errors either way...including when I tried to use the "into" parameter. I thought it would just be translated to the new skbio.io.read, but it's not working for me. Thanks!

**Comment by gregcaporaso** [comment]
Great!

On Thu, Oct 20, 2016 at 9:19 AM, Jennifer Fouquier <notifications@github.com

**Comment by jairideout** [comment]
You can use `TabularMSA` to read in a FASTA file like this:

```python
from skbio import TabularMSA, DNA

msa = TabularMSA.read('foo.fasta', constructor=DNA)
```

The next steps in your function are filtering positions based on gaps and entropy. This API has changed significantly -- it is much more powerful now and consistent (you can actually filter out things at 100% instead of using that `np.inf` hack we implemented with you!).

For gap-based filtering, check out [TabularMSA.gap_frequencies()](http://scikit-bio.org/docs/latest/generated/skbio.alignment.TabularMSA.gap_frequencies.html#skbio.alignment.TabularMSA.gap_frequencies). This can compute gap frequencies on either axis of the MSA -- it looks like you'll want the default behavior, `axis='sequence'`, which computes the frequency of gap characters for each position in the MSA (i.e., across the sequence axis). You'll receive a numpy vector of gap frequencies, which can then be converted into a boolean vector where each position in the vector is a `True` or `False` value indicating whether the position passes or fails your gap frequency filter. Something like: `positions_to_keep = gap_freqs <= maximum_gap_frequency`. This boolean vector can then be used to filter your MSA's positions with [TabularMSA.iloc](http://scikit-bio.org/docs/latest/generated/skbio.alignment.TabularMSA.iloc.html#skbio.alignment.TabularMSA.iloc), something like: `filtered_msa = msa.iloc[:, positions_to_keep]`, where `positions_to_keep` is your boolean vector.

We now support conservation-based filtering instead of entropy-based filtering via the [TabularMSA.conservation()](http://scikit-bio.org/docs/latest/generated/skbio.alignment.TabularMSA.conservation.html#skbio.alignment.TabularMSA.conservation) method. Filtering positions from the MSA can be achieved in a similar way as described above for gap frequencies.

See [this section on filtering](http://nbviewer.jupyter.org/github/biocore/scikit-bio-cookbook/blob/master/Alignment%20viewing%20and%20filtering.ipynb#Filtering-alignments) in the cookbook for more details/examples of filtering MSAs.

Let us know if you have other questions!

**Comment by JTFouquier** [comment]
Hey @jairideout!  Thanks so much for all the information. I'll definitely need this. It's been a while since I've regularly been working with ghost-tree, QIIME, or skbio (got sidetracked with web development the last year), so I'm pretty rusty. I'll let you know if I have any qs!!  Thank you!!

**Comment by JTFouquier** [comment]
Hey @jairideout or @gregcaporaso, I'm stuck on an issue that appears to be related to seq generators. Here is the console output (tons of print statements). I can see my seq generator (same hash every time, which makes sense), and it works on the code related to the first node of the foundation tree (three nodes total in the foundation test file, as you can see below), but then it will just not iterate through the generator on the second round. 

https://github.com/JTFouquier/ghost-tree/blob/python3_update/ghosttree/scaffold/hybridtree.py#L159

It won't do line 159 on subsequent "rounds", so I'm getting the same mini extension tree mini tree: **(P1:0.00027,P2:0.00027);**
 over and over.

Any generator tips?  Thanks! 

**Console Output:**

ghost-tree is running now...

foundation tree (PBB1:0.2289,MBB1:0.57748,CBB1:0.23576);

****************************

node:  PBB1:0.2289;

***mini otu files function:

seqs (only allows iteration once:  generator object IORegistry.read.<locals>.<genexpr> at 0x10889df68
keep:  ['P1', 'P2']
seq in seqs:  AAAAAAAA
seq in seqs:  AAGAAAAA
seq in seqs:  TTAAAAAA
seq in seqs:  AAAATTAA
seq in seqs:  AAAATTAA
seq in seqs:  AAGAAAAA
seq in seqs:  AAGAAAAA
seq in seqs:  ATATAAAA
seq in seqs:  TAAAAAAA
seq in seqs:  TTAAAAAA
FOUND MATCH
seq P1
seq in seqs:  AATTAAAA
FOUND MATCH
seq P2
std out muscle b''
std error muscle b''
std out ft b''
std error ft b''
**mini tree: (P1:0.00027,P2:0.00027);**

****************************

node:  MBB1:0.57748;

***mini otu files function:

seqs (only allows iteration once:  generator object IORegistry.read.<locals>.<genexpr at 0x10889df68>
keep:  ['M2', 'M3']
std out muscle b''
std error muscle b'\n*** ERROR ***  No sequences in input file\n'
std out ft b''
std error ft b''
**mini tree: (P1:0.00027,P2:0.00027);**

****************************

node:  CBB1:0.23576;

***mini otu files function:

seqs (only allows iteration once:  generator object IORegistry.read.<locals>.<genexpr at 0x10889df68>
keep:  ['C1', 'C2', 'C3', 'M1', 'C4', 'C5', 'M4']
std out muscle b''
std error muscle b'\n*** ERROR ***  No sequences in input file\n'
std out ft b''
std error ft b''
**mini tree: (P1:0.00027,P2:0.00027);**


...ghost-tree is complete.

**Comment by jairideout** [comment]
Python generators can only be iterated over / consumed once. After that, the generator will be empty. If you need to process the generator's contents more than once, one strategy is to convert the generator into something like a list, which can be iterated over any number of times. For example:

```python
items = list(gen) # `gen` is a generator
```

**Comment by JTFouquier** [comment]
@jairideout, ahhh, wow that was simple. You can see how regularly I've used generators. :)  Thanks!

**Comment by JTFouquier** [comment]
ghost-tree now uses skbio 5.1

**Comment by jairideout** [comment]
Awesome!! 🎉
